spring:
  datasource:
    url: jdbc:h2:mem:db-desafio-serasa-experian
    driverClassName: org.h2.Driver
    username: desafio-serasa-experian
    password: desafio-serasa-experian

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379

server:
  port: 8443
  ssl:
    key-alias: certificate
    key-store: classpath:certificate.jks
    key-store-type: JKS
    key-password: password
  servlet:
    encoding:
      charset: "UTF-8"

api.security.token.secret: ${my-secret-key}
password.admin: ${password-admin}
